export const opportunityTypes = [
  "Kamu alımı",
  "Belediye ilanı",
  "Özel sektör",
  "Staj",
  "Eğitim",
  "Yarışma",
  "Burs",
  "Meslek odası",
  "Gönüllülük",
  "Uzaktan çalışma",
  "Proje bazlı iş",
  "Akademik ilan",
  "Sözleşmeli personel",
  "Sürekli işçi alımı",
  "Uzman / uzman yardımcısı",
  "Engelli personel alımı",
  "Eski hükümlü işçi alımı",
  "Diğer",
];

export const professionAreas = [
  "Şehir ve Bölge Planlama",
  "Kentsel Tasarım",
  "CBS / GIS",
  "Harita Mühendisliği",
  "Geomatik Mühendisliği",
  "Mimarlık",
  "İç Mimarlık",
  "Peyzaj Mimarlığı",
  "İnşaat Mühendisliği",
  "Çevre Mühendisliği",
  "Makine Mühendisliği",
  "Elektrik Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Elektronik ve Haberleşme Mühendisliği",
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Endüstri Mühendisliği",
  "Kimya Mühendisliği",
  "Gıda Mühendisliği",
  "Ziraat Mühendisliği",
  "Orman Mühendisliği",
  "Jeoloji Mühendisliği",
  "Jeofizik Mühendisliği",
  "Maden Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Enerji Sistemleri Mühendisliği",
  "Ulaştırma Mühendisliği",
  "Biyomedikal Mühendisliği",
  "Mekatronik Mühendisliği",
  "Yazılım / Bilişim",
  "Veri Analizi",
  "Veri Bilimi",
  "Yapay Zeka",
  "Siber Güvenlik",
  "Sistem ve Ağ Yönetimi",
  "Web Geliştirme",
  "Mobil Uygulama Geliştirme",
  "UI / UX Tasarımı",
  "Ürün Yönetimi",
  "Ekonomi",
  "İktisat",
  "İşletme",
  "Maliye",
  "Muhasebe",
  "Finans",
  "Bankacılık",
  "Sigortacılık",
  "Uluslararası Ticaret",
  "Lojistik",
  "İnsan Kaynakları",
  "Satış ve Pazarlama",
  "Dijital Pazarlama",
  "Halkla İlişkiler",
  "Kamu Yönetimi",
  "Siyaset Bilimi",
  "Uluslararası İlişkiler",
  "Hukuk",
  "Sosyoloji",
  "Psikoloji",
  "Felsefe",
  "Tarih",
  "Coğrafya",
  "İstatistik",
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Eğitim Bilimleri",
  "Öğretmenlik",
  "Okul Öncesi Öğretmenliği",
  "Sınıf Öğretmenliği",
  "Türkçe Öğretmenliği",
  "Matematik Öğretmenliği",
  "İngilizce Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Tıp",
  "Hemşirelik",
  "Ebelik",
  "Diş Hekimliği",
  "Eczacılık",
  "Veteriner Hekimliği",
  "Fizyoterapi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Sağlık Yönetimi",
  "Sosyal Hizmet",
  "Laboratuvar Teknikleri",
  "Paramedik",
  "Anestezi",
  "Radyoloji",
  "Grafik Tasarım",
  "Endüstri Ürünleri Tasarımı",
  "Görsel İletişim Tasarımı",
  "Moda Tasarımı",
  "Reklamcılık",
  "Gazetecilik",
  "Radyo, Televizyon ve Sinema",
  "Yeni Medya",
  "Fotoğrafçılık",
  "Turizm ve Otelcilik",
  "Gastronomi",
  "Spor Bilimleri",
  "Güvenlik",
  "İş Sağlığı ve Güvenliği",
  "Tekniker / Teknisyen",
  "Büro Yönetimi",
  "Sekreterya",
  "Çağrı Merkezi",
  "Müşteri Hizmetleri",
  "Satın Alma",
  "Depo ve Stok Yönetimi",
  "Üretim",
  "Kalite Kontrol",
  "Diğer",
];

export const cities = [
  "Türkiye Geneli",
  "Uzaktan",
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Iğdır",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kilis",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Şanlıurfa",
  "Şırnak",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
  "Diğer",
];
