export const opportunityTypes = [
  "Kamu alımı",
  "Belediye ilanı",
  "Özel sektör",
  "Staj",
  "Eğitim",
  "Yarışma",
  "Burs",
  "Meslek odası",
  "Gönüllülük",
  "Uzaktan çalışma",
  "Proje bazlı iş",
  "Diğer",
];

export const professionAreas = [
  "Şehir ve Bölge Planlama",
  "Peyzaj Mimarlığı",
  "Mimarlık",
  "İç Mimarlık",
  "Kentsel Tasarım",
  "CBS / GIS",
  "Harita Mühendisliği",
  "İnşaat Mühendisliği",
  "Çevre Mühendisliği",
  "Ulaştırma Planlama",
  "Coğrafya",
  "Sosyoloji",
  "Kamu Yönetimi",
  "Ekonomi",
  "İstatistik",
  "Veri Analizi",
  "Yazılım / Bilişim",
  "Endüstri Ürünleri Tasarımı",
  "Grafik Tasarım",
  "Endüstri Mühendisliği",
  "Diğer",
];

export const cities = [
  "Türkiye Geneli",
  "Uzaktan",
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Iğdır",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kilis",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Şanlıurfa",
  "Şırnak",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
  "Diğer",
];
